Use Python port of code generator
DataDog/datadog-api-client-go pull request #1376
Opened 2022-03-08 15:40 UTC by jirikuncar

Rewrites code generator for Python + Jinja.

2022-03-14 17:52 UTC, therve requested changes

2022-03-14 17:52 UTC, therve commented on api/v1/datadog/model_monitor_search_count_item.go
> +type MonitorSearchCountItem struct {
It looks like an unused struct?

2022-03-15 15:52 UTC, jirikuncar commented on api/v1/datadog/model_monitor_search_count_item.go
> +type MonitorSearchCountItem struct {
No but nested arrays have a wrong name:

```golang
// MonitorGroupSearchResponseCounts The counts of monitor groups per different criteria.
type MonitorGroupSearchResponseCounts struct {
	// Search facets.
	Status *[]interface{} `json:"status,omitempty"`
	// Search facets.
	Type *[]interface{} `json:"type,omitempty"`
	// UnparsedObject contains the raw value of the object if there was an error when deserializing into the struct
	UnparsedObject       map[string]interface{} `json:-`
	AdditionalProperties map[string]interface{}
}
```

2022-03-16 08:55 UTC, jirikuncar commented on api/v1/datadog/model_monitor_search_count_item.go
> +type MonitorSearchCountItem struct {
I have fixed it now. 🙇

2022-03-16 10:10 UTC, therve approved these changes

2022-03-16 11:06 UTC, merged