Improve landing page
DataDog/datadog-api-client-go pull request #685
Opened 2021-01-29 12:50 UTC by therve

SSIA

2021-01-29 13:04 UTC, jirikuncar commented on README.md
> +            "name":     "api.datadoghq.eu",
```suggestion
            "site":     "api.datadoghq.eu",
```

2021-01-29 13:04 UTC, jirikuncar commented on README.md
> +            "protocol": "https",
```suggestion
```

2021-01-29 13:05 UTC, jirikuncar commented on README.md
> +    ctx = context.WithValue(ctx, datadog.ContextServerIndex, 1)
```suggestion
```

2021-02-09 08:46 UTC, zippolyte requested changes

2021-02-09 08:46 UTC, zippolyte commented on README.md
> +The client library for Datadog API v1 is located in the `api/v2/datadog` directory. Import it with
```suggestion
The client library for Datadog API v2 is located in the `api/v2/datadog` directory. Import it with
```

2021-02-09 08:47 UTC, zippolyte approved these changes

2021-02-09 08:54 UTC, merged