tests: bump dd-trace-go
DataDog/datadog-api-client-go pull request #757
Opened 2021-02-26 17:01 UTC by jirikuncar

The new version of `dd-trace-go` is sending `os.*` and `runtime.*` tags for detailed test information.

2021-02-26 17:02 UTC, jirikuncar commented
/azp run

2021-02-26 17:06 UTC, jirikuncar commented
/azp run

2021-03-01 14:20 UTC, zippolyte requested changes

2021-03-01 14:20 UTC, zippolyte commented on LICENSE-3rdparty.csv
> +go.sum,github.com/sirupsen/logrus,<LICENSE>,<COPYRIGHT>
Template values should be filled

2021-03-02 09:48 UTC, jirikuncar commented on LICENSE-3rdparty.csv
> +go.sum,github.com/sirupsen/logrus,<LICENSE>,<COPYRIGHT>
```suggestion
go.sum,github.com/Microsoft/go-winio,MIT,2015 Microsoft
go.sum,github.com/konsorten/go-windows-terminal-sequences,MIT,2017 marvin + konsorten GmbH
go.sum,github.com/sirupsen/logrus,MIT,2014 Simon Eskildsen
```

2021-03-02 09:48 UTC, jirikuncar commented on LICENSE-3rdparty.csv
> +
```suggestion
```

2021-03-02 09:48 UTC, jirikuncar commented
/azp run

2021-03-02 09:59 UTC, merged